// Optional pre-baked 48-month vacancy sparklines (plan A-iii), keyed by ParcelId.
// Generated by `npm run data:timelines`. If the file is absent (404), the
// ScorePanel transparently falls back to the live 48× backDate recompute.
import { TIMELINES_URL } from "@/config/constants";

let cache: Record<string, number[]> = {};
let promise: Promise<Record<string, number[]>> | null = null;

export function loadTimelines(): Promise<Record<string, number[]>> {
  if (!promise) {
    promise = fetch(TIMELINES_URL)
      .then((r) => (r.ok ? r.json() : {}))
      .catch(() => ({}))
      .then((t: Record<string, number[]>) => {
        cache = t;
        return t;
      });
  }
  return promise;
}

export function getPrebakedTimeline(parcelId: string): number[] | null {
  return cache[parcelId] ?? null;
}
